---
- name: install postgresql
  apt:
    pkg: "{{ item }}"
    state: installed
  with_items:
    - postgresql
    - postgresql-common
    - postgresql-client
    - postgresql-client-common

- name: start postgresql
  service:
    name: postgresql
    state: started

- name: create umsatz database
  sudo_user: postgres
  postgresql_db:
    name: "{{ database }}"
    encoding: 'UTF-8'
    lc_collate: 'en_US.UTF-8'
    lc_ctype: 'en_US.UTF-8'
    template: 'template0'

- name: create umsatz db user
  sudo_user: postgres
  postgresql_user:
    db: "{{ database }}"
    name: "{{ database_user }}"
    password: "{{ database_password }}"
    priv: ALL